FROM python:3.11-slim

WORKDIR /application

# main page
COPY ./main.py /application

# pages
COPY ./pages /application/pages

# api setup
COPY ./app/api_setup/dataclasses_api /application/app/api_setup/dataclasses_api


# .streamlit
COPY ./.streamlit /application/.streamlit

# requirements
COPY ./requirements/requirements_streamlit.txt /application/requirements.txt

RUN pip install --no-cache-dir -r /application/requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "main.py"]